### ISSUE TITLE
After update to v1.14 pin location is not shown

### ISSUE THREAD

**Issue by Onigar** [ESOUIMods/ScrySpy#4] opened 2020-06-08 04:10 UTC
this is just feedback but after updating to 1.14 from 1.13 a pin location is no longer shown.

I looked in my saved vars and there is still lots of locations stored so that seems fine.

The pin location was Stonefalls, Varanis dolmen. just left of the witches hut.
This is a small area. I did this same area both yesterday and today so memory is still fresh.

saved vars file uploaded.

Note: cannot drag and drop a lua file. "we don't support that file type"

just remove the .txt extension

[ScrySpy.lua.txt](https://github.com/ESOUIMods/ScrySpy/files/4743793/ScrySpy.lua.txt)

**Comment by Sharlikran** [comment] 2020-06-08 08:37
@Onigar Now go to that location on your map. You don't need to be scrying, just go where you know it is supposed to be. Once there get a screen shot of the map. Don't zoom in though. Then using pain or something draw a circle around your char so I don't miss it with my old eyes.

I would like a screen shot of where you are standing where you expect the digsites to be please.

**Comment by Onigar** [comment] 2020-06-08 15:38
In the first image there is someone digging in the location I am talking about.
![Screenshot_20200608_170055](https://user-images.githubusercontent.com/41226484/84050771-788afe00-a9ae-11ea-95a7-140466cd2556.png)
![Screenshot_20200608_170112](https://user-images.githubusercontent.com/41226484/84050920-b12ad780-a9ae-11ea-9861-bef91c06d5ab.png)

**Comment by Onigar** [comment] 2020-06-08 15:39
did not mean to close

**Comment by Sharlikran** [comment] 2020-06-08 21:32
### Pic of the pin in question

![Screenshot_20200608_091506](https://user-images.githubusercontent.com/1912426/84080484-18d22a00-a991-11ea-8c54-348bededd021.png)

### Thoughts

Since I know you from Gitter I figure you would not manually edit your pins. So they have been added to the mod. 

There isn't a way for me to really know enough about the polygon. ZOS Dan just told me there is a function to get the center point so I will try to use that in an update if I can figure out how to call it and what arguments is needs if any.

The other reason I added them is that I am looking to determine whether or not pins show up from your SavedVariables file. So now that most of your pins are in the main database when you add a new pin that isn't in the database I wonder if it will show up when you scry in that location again.

### Request

What I would like you to do is make a backup of your SavedVariables file and then go do your daily scrying. Any pin recorded will not be a duplicate of the main database. So it would be a good way to tell if pins from SavedVariables are being shown or not.

**Comment by Sharlikran** [comment] 2020-07-08 15:27
This should be addressed already.

**Closed by Sharlikran** 2020-07-08 15:27 UTC
